#
# Derived from
# https://github.com/steveno/ctags/blob/master/.travis.yml
#
language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y binutils-mingw-w64-i686 gcc-mingw-w64-i686
env:
  - TARGET=Unix
  - TARGET=Mingw32
script:
  - autoreconf -f -i -v
  - ./configure
  - ./misc/travis.sh
matrix:
  exclude:
    - compiler: clang
      env: TARGET=Mingw32
